// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companies.proto

package com.berza.grpc;

public interface AskDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AskData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Symbol = 1;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string Symbol = 1;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>double Price = 2;</code>
   */
  double getPrice();

  /**
   * <code>int32 Amount = 3;</code>
   */
  int getAmount();

  /**
   * <code>string clientId = 4;</code>
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 4;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
