// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companies.proto

package com.berza.grpc;

public interface AskListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AskList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  java.util.List<com.berza.grpc.AskData> 
      getAsksList();
  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  com.berza.grpc.AskData getAsks(int index);
  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  int getAsksCount();
  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  java.util.List<? extends com.berza.grpc.AskDataOrBuilder> 
      getAsksOrBuilderList();
  /**
   * <code>repeated .AskData asks = 1;</code>
   */
  com.berza.grpc.AskDataOrBuilder getAsksOrBuilder(
      int index);
}
