// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companies.proto

package com.berza.grpc;

public interface AskReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AskReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Symbol = 1;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string Symbol = 1;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>int32 Amount = 2;</code>
   */
  int getAmount();
}
