// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companies.proto

package com.berza.grpc;

public interface BidListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BidList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .OrderRequest orders = 1;</code>
   */
  java.util.List<com.berza.grpc.OrderRequest> 
      getOrdersList();
  /**
   * <code>repeated .OrderRequest orders = 1;</code>
   */
  com.berza.grpc.OrderRequest getOrders(int index);
  /**
   * <code>repeated .OrderRequest orders = 1;</code>
   */
  int getOrdersCount();
  /**
   * <code>repeated .OrderRequest orders = 1;</code>
   */
  java.util.List<? extends com.berza.grpc.OrderRequestOrBuilder> 
      getOrdersOrBuilderList();
  /**
   * <code>repeated .OrderRequest orders = 1;</code>
   */
  com.berza.grpc.OrderRequestOrBuilder getOrdersOrBuilder(
      int index);
}
