// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companies.proto

package com.berza.grpc;

public interface CompanyListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CompanyList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Company companies = 1;</code>
   */
  java.util.List<com.berza.grpc.Company> 
      getCompaniesList();
  /**
   * <code>repeated .Company companies = 1;</code>
   */
  com.berza.grpc.Company getCompanies(int index);
  /**
   * <code>repeated .Company companies = 1;</code>
   */
  int getCompaniesCount();
  /**
   * <code>repeated .Company companies = 1;</code>
   */
  java.util.List<? extends com.berza.grpc.CompanyOrBuilder> 
      getCompaniesOrBuilderList();
  /**
   * <code>repeated .Company companies = 1;</code>
   */
  com.berza.grpc.CompanyOrBuilder getCompaniesOrBuilder(
      int index);
}
