// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companies.proto

package com.berza.grpc;

public interface CompanyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Company)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Symbol = 1;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string Symbol = 1;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string Name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string Name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double Price = 3;</code>
   */
  double getPrice();

  /**
   * <code>double Change = 4;</code>
   */
  double getChange();

  /**
   * <code>.google.protobuf.Timestamp Date = 5;</code>
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp Date = 5;</code>
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp Date = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

  /**
   * <code>double PreviousPrice = 6;</code>
   */
  double getPreviousPrice();

  /**
   * <code>repeated double History = 7;</code>
   */
  java.util.List<java.lang.Double> getHistoryList();
  /**
   * <code>repeated double History = 7;</code>
   */
  int getHistoryCount();
  /**
   * <code>repeated double History = 7;</code>
   */
  double getHistory(int index);
}
