// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companies.proto

package com.berza.grpc;

public interface NoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:None)
    com.google.protobuf.MessageOrBuilder {
}
