// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companies.proto

package com.berza.grpc;

public interface OfferRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OfferRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string buyerId = 1;</code>
   */
  java.lang.String getBuyerId();
  /**
   * <code>string buyerId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBuyerIdBytes();
}
