// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companies.proto

package com.berza.grpc;

public interface OfferListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OfferList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .OrderRequest offers = 1;</code>
   */
  java.util.List<com.berza.grpc.OrderRequest> 
      getOffersList();
  /**
   * <code>repeated .OrderRequest offers = 1;</code>
   */
  com.berza.grpc.OrderRequest getOffers(int index);
  /**
   * <code>repeated .OrderRequest offers = 1;</code>
   */
  int getOffersCount();
  /**
   * <code>repeated .OrderRequest offers = 1;</code>
   */
  java.util.List<? extends com.berza.grpc.OrderRequestOrBuilder> 
      getOffersOrBuilderList();
  /**
   * <code>repeated .OrderRequest offers = 1;</code>
   */
  com.berza.grpc.OrderRequestOrBuilder getOffersOrBuilder(
      int index);
}
