// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companies.proto

package com.berza.grpc;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string buyerClientId = 1;</code>
   */
  java.lang.String getBuyerClientId();
  /**
   * <code>string buyerClientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBuyerClientIdBytes();

  /**
   * <code>string sellerClientId = 2;</code>
   */
  java.lang.String getSellerClientId();
  /**
   * <code>string sellerClientId = 2;</code>
   */
  com.google.protobuf.ByteString
      getSellerClientIdBytes();

  /**
   * <code>string symbol = 3;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 3;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>double price = 4;</code>
   */
  double getPrice();

  /**
   * <code>int32 quantity = 5;</code>
   */
  int getQuantity();

  /**
   * <code>bool status = 6;</code>
   */
  boolean getStatus();

  /**
   * <code>string orderId = 7;</code>
   */
  java.lang.String getOrderId();
  /**
   * <code>string orderId = 7;</code>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();
}
