// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companies.proto

package com.berza.grpc;

public interface StockInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>int32 notForSale = 2;</code>
   */
  int getNotForSale();

  /**
   * <code>int32 forSale = 3;</code>
   */
  int getForSale();
}
