// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companies.proto

package com.berza.grpc;

public interface SubscriptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubscriptionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ClientId = 1;</code>
   */
  java.lang.String getClientId();
  /**
   * <code>string ClientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>repeated string Symbols = 2;</code>
   */
  java.util.List<java.lang.String>
      getSymbolsList();
  /**
   * <code>repeated string Symbols = 2;</code>
   */
  int getSymbolsCount();
  /**
   * <code>repeated string Symbols = 2;</code>
   */
  java.lang.String getSymbols(int index);
  /**
   * <code>repeated string Symbols = 2;</code>
   */
  com.google.protobuf.ByteString
      getSymbolsBytes(int index);
}
