// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companies.proto

package com.berza.grpc;

public interface UpdateStockAmountsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateStockAmountsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientId = 1;</code>
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>string symbol = 2;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 2;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>int32 newForSaleValue = 3;</code>
   */
  int getNewForSaleValue();

  /**
   * <code>int32 newNotForSaleValue = 4;</code>
   */
  int getNewNotForSaleValue();
}
